---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - vault.banzaicloud.com
  resources:
  - vaults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.banzaicloud.com
  resources:
  - vaults/finalizers
  verbs:
  - update
- apiGroups:
  - vault.banzaicloud.com
  resources:
  - vaults/status
  verbs:
  - get
  - patch
  - update
