# permissions for end users to edit vaults.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vault-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: myoperator
    app.kubernetes.io/part-of: myoperator
    app.kubernetes.io/managed-by: kustomize
  name: vault-editor-role
rules:
- apiGroups:
  - vault.banzaicloud.com.rossoperator.io
  resources:
  - vaults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.banzaicloud.com.rossoperator.io
  resources:
  - vaults/status
  verbs:
  - get
