apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vaultmon-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vaultmon
    app.kubernetes.io/part-of: vaultmon
    app.kubernetes.io/managed-by: kustomize
  name: vaultmon-viewer-role
rules:
- apiGroups:
  - rossoperator.io
  resources:
  - vaultmons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rossoperator.io
  resources:
  - vaultmons/status
  verbs:
  - get
